<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Profanity Filter Configuration
    |--------------------------------------------------------------------------
    |
    |
    */

    /* Disable to replace partial words. */
    'replaceFullWords' => true,

    /* Replace bad words with this, based on length of word */
    'replaceWith' => '*',

    /* Replace related letters */
    'strReplace' => [
            'a' => '(a|a\.|a\-|4|@|Á|á|À|Â|à|Â|â|Ä|ä|Ã|ã|Å|å|α|Δ|Λ|λ)',
            'b' => '(b|b\.|b\-|8|\|3|ß|Β|β)',
            'c' => '(c|c\.|c\-|Ç|ç|¢|€|<|\(|{|©)',
            'd' => '(d|d\.|d\-|&part;|\|\)|Þ|þ|Ð|ð)',
            'e' => '(e|e\.|e\-|3|€|È|è|É|é|Ê|ê|∑)',
            'f' => '(f|f\.|f\-|ƒ)',
            'g' => '(g|g\.|g\-|6|9)',
            'h' => '(h|h\.|h\-|Η)',
            'i' => '(i|i\.|i\-|!|\||\]\[|]|1|∫|Ì|Í|Î|Ï|ì|í|î|ï)',
            'j' => '(j|j\.|j\-)',
            'k' => '(k|k\.|k\-|Κ|κ)',
            'l' => '(l|1\.|l\-|!|\||\]\[|]|£|∫|Ì|Í|Î|Ï)',
            'm' => '(m|m\.|m\-)',
            'n' => '(n|n\.|n\-|η|Ν|Π)',
            'o' => '(o|o\.|o\-|0|Ο|ο|Φ|¤|°|ø)',
            'p' => '(p|p\.|p\-|ρ|Ρ|¶|þ)',
            'q' => '(q|q\.|q\-)',
            'r' => '(r|r\.|r\-|®)',
            's' => '(s|s\.|s\-|5|\$|§)',
            't' => '(t|t\.|t\-|Τ|τ)',
            'u' => '(u|u\.|u\-|υ|µ)',
            'v' => '(v|v\.|v\-|υ|ν)',
            'w' => '(w|w\.|w\-|ω|ψ|Ψ)',
            'x' => '(x|x\.|x\-|Χ|χ)',
            'y' => '(y|y\.|y\-|¥|γ|ÿ|ý|Ÿ|Ý)',
            'z' => '(z|z\.|z\-|Ζ)',
    ],

    /* Replace these words no matter what language. */
    'defaults' => [
        ''
    ],

    /* All banned words. */
    'banned' => [
        'shit',
        'fuck',
        'fucker',
        'fucking',
        'fucks',
        'fuckers',
        'nigger',
        'niggers',
        'motherfucker',
        'asshole',
        'Assface',
        'asswipe',
        'assholes',
        'pussy',
        'faggot',
        'faggots',
        'fags',
        'fag',
        'fuckin',
        'nigga',
        'cockhead',
        'cock-head',
        'CockSucker',
        'cock-sucker',
        'cunt',
        'cunts',
        'cock',
        'cocks',
        'shitty',
        'shittiest',
        'shits',
        'ass',
        'bitch',
        "bitch's",
        'bitches',
        'bitchs',
        'cock gobbler',
        'lesbionic',
        'dickhead',
        'dick head',
        'dickheads',
        'dick heads',
        'dickhole',
        'dick hole',
        'gurgle monster',
        'cum dumpster',
        'Carpet Muncher',
        'fatass',
        'fat-ass',
        'slut',
        'Blow Job',
        'Clit',
        'dildo',
        'jackoff',
        'jerk-off',
        'blow jobs',
        'anus',
        'bastard',
        'bastards',
        'butthole',
        'buttwipe',
        'crap',
        'God Damn',
        'God Damned',
        'God Damnit',
        'slut',
        'sluts',
        'Slutty',
        'jizz',
        'testicle',
        'butt-pirate',
        'nutsack',
        'nuttsack',
        'ahole',
        'ash0le',
        'ash0les',
        'asholes',
        'assh0le',
        'assh0lez',
        'assholz',
        'azzhole',
        'bassterds',
        'bastardz',
        'basterds',
        'basterdz',
        'Biatch',
        'c0ck',
        'c0cks',
        'c0k',
        'cawk',
        'cawks',
        'cuntz',
        'dild0',
        'dild0s',
        'dildos',
        'dilld0',
        'dilld0s',
        'f u c k',
        'f u c k e r',
        'f u c k i n g',
        'fag1t',
        'faget',
        'fagg1t',
        'faggit',
        'fagit',
        'fagz',
        'faig',
        'faigs',
        'Fudge Packer',
        'fuk',
        'Fukah',
        'Fuken',
        'fuker',
        'Fukin',
        'Fukk',
        'Fukker',
        'Fukkin',
        'jizm',
        'slutz',
        'assopedia',
        'Kunyuk', 
        'Bajingan', 
        'Asu', 
        'Bangsat', 
        'Kampret', 
        'Kontol', 
        'Memek', 
        'Ngentot', 
        'Pentil', 
        'Perek', 
        'Pepek', 
        'Pecun', 
        'Bencong', 
        'Banci', 
        'Maho', 
        'Gila', 
        'Sinting', 
        'Tolol', 
        'Sarap', 
        'Setan', 
        'Lonte', 
        'Hencet', 
        'Taptei', 
        'Kampang', 
        'Pilat', 
        'Keparat', 
        'Bejad', 
        'Gembel', 
        'Brengsek', 
        'Tai', 
        'Anjrit', 
        'Bangsat', 
        'Fuck', 
        'Tetek', 
        'Ngulum', 
        'Jembut', 
        'Totong', 
        'Kolop', 
        'Pukimak', 
        'Bodat', 
        'Heang', 
        'Jancuk', 
        'Burit', 
        'Titit', 
        'Nenen', 
        'Bejat', 
        'Silit', 
        'Sempak', 
        'Fucking', 
        'Asshole', 
        'Bitch', 
        'Penis', 
        'Vagina', 
        'Klitoris', 
        'Kelentit', 
        'Borjong', 
        'Dancuk', 
        'Pantek', 
        'Taek', 
        'Itil', 
        'Teho', 
        'Bejat', 
        'Pantat', 
        'Bagudung', 
        'Babami', 
        'Kanciang', 
        'Bungul', 
        'Idiot', 
        'Kimak', 
        'Henceut', 
        'Kacuk', 
        'Blowjob', 
        'Dick', 
        'Damn', 
    ],
];
